### ISSUE TITLE
Cannot disable ivi module with disabled_modules[] = ivi

### ISSUE THREAD

**Issue by javiermatos** [azhurb/stalker_portal#124]
Hello again,

I was disabling modules by adding disabled_modules[] in custom.ini and it was ok for all of them. I found that I cannot disable ivi module by adding disabled_modules[] = ivi. I had to comment all_modules[] = ivi in config.ini to really disable it.

Regards,
Javier

**Comment by azhurb** [comment]
Hello.

IVI application, according to the terms with ivi.ru, is a special module, which can not be added to the tariff plan or disabled via additional service option. It can only be accessable for all users or disabled for all users, that is why you have to delete it from all_modules.

**Comment by javiermatos** [comment]
Thank you for the info :)

**Comment by madonak** [comment]
As per the documentation, there should be a setting that can be added to
custom.ini to enable/disable it on a system wide basis, since the
documentation very clearly states not to edit config.ini directly, and
moving all_modules to custom.ini in it's entirety is also not an
appropriate fix for disabling it.
